### ISSUE TITLE
Add map `entry` APIs

### ISSUE THREAD

**Issue by tnballo** [tnballo/scapegoat#15]
To mirror `BTreeMap`'s [`entry`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.entry), [`first_entry`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.first_entry), and [`last_entry`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.last_entry).

**Comment by TheDoctor314** [comment]
Hi! I'd like to work on this.

**Comment by tnballo** [comment]
Hey! Awesome, thank you - I'll assign the issue to you. To help you navigate the code:

* `src/tree/tree.rs` is where the majority of the logic is implemented, both sets and maps are mostly public wrappers around this tree.
    * Since v2.0, this module is internal-only (not part of crate's public API). So you're free to make any changes necessary.
    * This where you'll find `self.min_idx` and `self.max_idx`, array indexes (e.x. `&self.arena[self.min_idx]`) that the help access the first/minimum and last/maximum items (useful for `first_entry` and `last_entry`).

* `src/map_types.rs` is where `SgMap`'s return types are. This is a good place to define a public [`Entry` struct](https://doc.rust-lang.org/std/collections/btree_map/enum.Entry.html), even if you decide to put most of the logic elsewhere.

Two asides:

* One of the main ways this crate is tested is by fuzzing against the standard library. I'd be happy to accept a PR even if it doesn't update the fuzz harness, so you don't need to worry about this. But, in case you find fuzzing helpful in testing the APIs you add: [this section](https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html) of the "Rust Fuzz" book explains structure-aware fuzzing, which is used in `fuzz/fuzz_targets/sg_map.rs`.

* `first_entry` and `last_entry` are currently nightly-only for `BTreeMap`, so if you can implement those APIs in this crate (stable 1.55+) I think that's pretty exciting :sunglasses:

Feel free to take you time on a PR since this isn't a bug/blocking. If you have any questions, I'll do my best to answer them on this thread but may not always reply same-day. Thanks for your time/effort!
