### ISSUE TITLE
Add `range` APIs

### ISSUE THREAD

**Issue by tnballo** [tnballo/scapegoat#17]
To mirror `BTreeSet`'s [`range`](https://doc.rust-lang.org/stable/std/collections/struct.BTreeSet.html#method.range), and `BTreeMap`'s [`range`](https://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html#method.range)/[`range_mut`](https://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html#method.range_mut).

To help navigate the codebase:

* `src/tree/tree.rs` is where the majority of logic is implemented, both sets and maps are public wrappers around this tree. Since v2.0, this module is internal-only (not part of crate's public API). So you're free to make any changes necessary to support the `range` APIs. Current iterator implementations live in `src/tree/iter.rs`.

* Return types like [`Range`](https://doc.rust-lang.org/std/collections/btree_map/struct.Range.html) should be added to `src/set_types.rs` and `src/map_types.rs`.

**Comment by TheDoctor314** [comment]
I'd like to work on this.

**Comment by tnballo** [comment]
Sweet, welcome back! Assigned to you.
